### ISSUE TITLE
How to save the generated image into NIfTI  format.

### ISSUE THREAD

**Issue by malaifa** [Medical-Image-Analysis-Laboratory/FaBiAN#5]
Hi,
This is a very good job. 
I do not know how to save the generated image into NIfTI  format.
Can anyone help me.
Thanks.

**Comment by helenelajous** [comment]
Dear @malaifa, you will find the answer to your question in the latest release of FaBiAN (FaBiAN v2.0). You can use directly the niftiwrite function to save the generated images into NIfTI format with the appropriate affine matrix. Examples are given in the main script as well as in the mat2nii.m function. Good luck!
